alias gs='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git commit -m'
alias gd='git diff'
alias go='git checkout'
alias gf='git fetch'
alias gfom='git fetch origin master'
alias gr='git rebase'
alias grom='git rebase origin/master'
alias gp='git push'
alias gpom='git push origin master'
alias gk='gitk --all&'
alias gx='gitx --all'

alias ni='npm install'
alias nis='npm install --save'
alias nid='npm install --save-dev'
alias nig='npm install --global'
alias nt='npm test'
alias nit='npm install && npm test'
alias nk='npm link'
alias nr='npm run'
alias ns='npm start'
alias nf='rm -rf node_modules && npm install'
alias nlg='npm list --global --depth=0'

alias ..='cd ../..';
alias ...='cd ../../..';
alias ....='cd ../../../../';
